In [ ]:
import pandas
import time
import random
import pickle
import requests
import tqdm

In [ ]:
with open('countries.pickle','rb') as fp:
    countries = pickle.load(fp)

In [ ]:
filename = 'C:\\Users\\alexa\\Documents\\UTC\\IM04 - Depart etranger\\US02\\Data-sheet-STUDENTS.xlsx'
df = pandas.read_excel(filename, header = 2, usecols = 'B:AR')

In [26]:
def get_indicator(country_code,indicator):
    head = 'http://api.worldbank.org/v2/country/'
    middle = '/indicator/'
    tail = '?format=json'
    url = head+country_code+middle+indicator+tail
    r = requests.get(url)
    try:
        data = r.json()
        for i in data[1]:
            if i['value'] is None:
                continue
            else:
                return i['value']
    except KeyError:
        return None
    except IndexError:
        return None
    
get_indicator('CHN','GC.TAX.IMPT.ZS')

3.89434134127694

In [31]:
for i,v in df['Country (according to CN Gov):'].iteritems():
    country_name = v.split('(')[0].strip()
    country_code = countries[country_name]
    value = get_indicator(country_code,'GC.TAX.IMPT.ZS')
    if value is not None:
        df.at[i,'IMF WB\nCustoms and other import duties (% of tax revenue) 2016'] = value
    print(country_name,'done...')
    time.sleep(0.5)
df[['Country (according to CN Gov):','IMF WB\nCustoms and other import duties (% of tax revenue) 2016']]

Afghanistan done...
Albania done...
Armenia done...
Azerbaijan done...
Bahrain done...
Bangladesh done...
Belarus done...
Bhutan done...
Bosnia and Herzegovina done...
Brunei done...
Bulgaria done...
Cambodia done...
China done...
Croatia done...
Czech Republic done...
East Timor done...
Egypt done...
Estonia done...
France done...
Georgia done...
Germany done...
Hungary done...
India done...
Indonesia done...
Iran done...
Iraq done...
Israel done...
Jordan done...
Kazakhstan done...
Kuwait done...
Kyrgyzstan done...
Laos done...
Latvia done...
Lebanon done...
Lithuania done...
Macedonia done...
Malaysia done...
Maldives done...
Moldova done...
Mongolia done...
Montenegro done...
Myanmar done...
Nepal done...
Oman done...
Pakistan done...
Philippines done...
Poland done...
Qatar done...
Romania done...
Russia done...
Saudi Arabia done...
Serbia done...
Singapore done...
Slovakia done...
Slovenia done...
Sri Lanka done...
Syria done...
Tajikistan done...
Thailiand done...
The United Arab Emirates done...
Turkey done...
Turkmenistan done...
United Kingdom done...
United States of America done...
Ukraine done...
Uzbekistan done...
Vietnam done...
Yemen done...

,Country (according to CN Gov):,IMF WB Customs and other import duties (% of tax revenue) 2016
0,Afghanistan,32.551072
1,Albania,2.216459
2,Armenia,6.275395
3,Azerbaijan,4.550383
4,Bahrain,87.914439
5,Bangladesh,28.923008
6,Belarus,8.200619
7,Bhutan,3.052294
8,Bosnia and Herzegovina,0.066132
9,Brunei,NaN
10,Bulgaria,0.072798
11,Cambodia,15.785253
12,China,3.894341
13,Croatia,0.670090
14,Czech Republic,0.819567
15,East Timor,5.741272
16,Egypt,6.849002
17,Estonia,0.039429
18,France (Not BRI),-0.021908
19,Georgia,0.796325
20,Germany (not BRI),0.021249
21,Hungary,-0.000145
22,India,NaN
23,Indonesia,2.463390
24,Iran,20.696450
25,Iraq,14.105211
26,Israel,1.153110
27,Jordan,8.533450
28,Kazakhstan,5.299908
29,Kuwait,66.806723
...,...,...
38,Moldova,3.423233
39,Mongolia,12.087573
40,Montenegro,NaN
41,Myanmar,9.003222
42,Nepal,17.770038
43,Oman,28.368146
44,Pakistan,18.780936
45,Philippines,20.357608
46,Poland,0.128546
47,Qatar,6.021326
48,Romania,0.003434
49,Russia,6.217626
50,Saudi Arabia,NaN
51,Serbia,5.062219
52,Singapore,0.071508
53,Slovakia,0.000290
54,Slovenia,0.808280
55,Sri Lanka,22.054891
56,Syria,10.230756
57,Tajikistan,NaN
58,Thailiand,3.952757
59,The United Arab Emirates,0.381747
60,Turkey,2.418238
61,Turkmenistan,NaN
62,United Kingdom (Not BRI),0.047747
63,United States of America (Not BRI),1.656294
64,Ukraine,3.997681
65,Uzbekistan,5.186860
66,Vietnam,18.427549
67,Yemen,NaN

In [30]:
df.columns

Index(['Country (according to CN Gov):', 'Date of research inquiry',
       'HF Index of Economic Freedom (Scale: 1-100)',
       'Heritage Foundation Index of Economic Freedom (Global Ranking)',
       'Bertelsmann Transformation index (BTI)',
       'Bertelsmann Transformation index (BTI) - Ranking',
       'IMF WB\nCustoms and other import duties (% of tax revenue) 2016',
       'WB IMF Non-performing loans to total gross loans ratio (%)',
       'Moody's Socvereign Ratings List', 'S&P Sovereign Ratings List',
       'Fitch Sovereign Ratings List',
       'UIC Rail freight (mn ton x km travelled)',
       'ICAO air freight (mn ton x km travelled)',
       'WB Household final consumption expenditure, PPP bn USD',
       'WB UNESCO R&D Expenditure % of GDP',
       'WB UNESCO Researchers p. mn inhabitants',
       'TI Corruption Perception Index',
       'TI Corruption Perception Index - Ranking', 'BRI GDP', 'BRI GDP p.c.',
       'BRI GDP growth rate', 'BRI Y.o.Y. GDP growth rate p.c.',
       'BRI Agriculture value added per sector ',
       'BRI Industry value added per sector ',
       'BRI Services value added per sector ',
       'Cumulative value added (numbers should reflect 100%)',
       'Exp./Imp. volume USD', 'WITS Time to Import ', 'WITS Time to Export ',
       'IMF Financial Soundness Indicators', 'WB Central Government Debt',
       'BRI Internet penetration rate (%)', 'BRI Population density (/km2)',
       'BRI Percentage of Urban Population in Total Population',
       'WB Cost of Starting a Business',
       'WB Ease of Doing Business Index (1 = most business-friendly regulations)',
       'WB Logistics Performance Index (LPI) (range: 1-5) ',
       'IFDI Net Inflows (% of GDP)',
       'ED National Electric Power Consumption TwH',
       'WHO Current Health Expenditure p.c., PPP USD',
       'WB Research Expenditure % of GDP', 'WIPO Trademark applications',
       'WIPO Patent Applications'],
      dtype='object')